#! /bin/sh
### BEGIN INIT INFO
# Provides:          slideshow
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

### I am going to test out the Start services, so I am going to comment out everything below this line###

case "$1" in
    start)
        cd /home/pi/SlideshowSoftware/pictures
        ./slideshow.sh &
   ;;
    stop)
        for i in `ps aux | grep './slideshow.sh' | grep -v grep | awk '{print $2}'`
      	 do
	chvt 1

          kill -9 $i
        done
        killall -9 fbi
	stty sane
	tput rs1
	alias fix='echo -e "\033c"'
	. ~/.bashrc
	tset



    ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
